server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: ${CONSUMER_GROUP:kafka-service-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
  kafka:
    prompt-topic: ${PROMPT_TOPIC:prompt_requests}
    response-topic: ${RESPONSE_TOPIC:llm_raw_responses}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics