apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ .Values.fullnameOverride }}-ap
  namespace: {{ $.Values.namespace | default $.Release.Namespace }}
spec:
  action: ALLOW
  rules:
    - to:
        - operation:
            methods:
            {{- range $.Values.authorizationPolicy.methods }}
            - {{ . }}
            {{- end }}
            paths:
              - /*
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.fullnameOverride }}