{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ .Values.fullnameOverride }}
  labels:
    {{- include "sample-app1.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.svc }}@{{ .Values.serviceAccount.projectId }}.iam.gserviceaccount.com
{{- end }}