apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-app1.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "sample-app1.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sample-app1.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sample-app1.selectorLabels" . | nindent 8 }}
          {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
          {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      automountServiceAccountToken: true
      serviceAccountName: {{ include "sample-app1.serviceAccountName" . }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}

          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP

          env:
            {{- if .Values.commonEnvVars }}
              {{- toYaml .Values.commonEnvVars | nindent 12 }}
              {{- end }}
              {{- if .Values.extraEnvVars }}
              {{- toYaml .Values.extraEnvVars | nindent 12 }}
              {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          {{- if .Values.probes.livenessEnabled }}
          {{- with .Values.probes.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}

          {{- if .Values.probes.readinessEnabled }}
          {{- with .Values.probes.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}